### ISSUE TITLE
Examples Code

### ISSUE THREAD

**Issue by indygwyn** [brownpapertickets/BptAPI.php#2]
Is it possible to get some examples of use?

**Comment by chantron** [comment]
Sure, I can work something up. Is there anything in particular you want to see in action?

**Comment by indygwyn** [comment]
Well for myself I'd love to see something accessing the sales API, but anything would give me enough of a hint to figure the rest out

**Comment by chantron** [comment]
I've just created a repo for a simple example app: https://github.com/brownpapertickets/api-example

Let me know if that's of any help (on that repo's issues page or shoot me an email!)
